return {
	["On"] = {
		[true] = {
			["Frame"] = {
				["BackgroundTransparency"] = 0	
			},

			["UIStroke"] = {
				["Transparency"] = 0;
			},

			["ImageLabel"] = {
				["ImageTransparency"] = 0
			}
		},
		[false] = {
			["Frame"] = {
				["BackgroundTransparency"] = 1	
			},

			["UIStroke"] = {
				["Transparency"] = 1;
			},

			["ImageLabel"] = {
				["ImageTransparency"] = 1
			}
		}
	},

	["Off"] = {
		[true] = {
			["Frame"] = {
				["BackgroundTransparency"] = 0	
			},

			["UIStroke"] = {
				["Transparency"] = 0.6;
			},

			["ImageLabel"] = {
				["ImageTransparency"] = 0.9
			}
		},
		[false] = {
			["Frame"] = {
				["BackgroundTransparency"] = 1	
			},

			["UIStroke"] = {
				["Transparency"] = 1;
			},

			["ImageLabel"] = {
				["ImageTransparency"] = 1
			}
		}
	}
}